TimestampTz must be in UTC.
Convert DateTimeOffset to DateTime UTC to prevent npgsql exception storing DateTimeOffset as
TimestampTz with npgsql 6.*:

InvalidCastException: Cannot write DateTimeOffset with Offset=02:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

https://www.npgsql.org/doc/types/datetime.html

The npgsql <6.0.0 behavior was to silently **discard** the offset component!